FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip && \
    python3 -m pip install kafka-python==2.0.2 && \
    python3 -m pip install requests